<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.6 on win32)" generated="20221026 12:44:05.892" rpa="false" schemaversion="3">
<suite id="s1" name="Serialtest" source="c:\project1\First_Repo\serialtest.robot">
<test id="s1-t1" name="Test case for connection" line="6">
<kw name="modbus.connection">
<var>${connection}</var>
<arg>a</arg>
<msg timestamp="20221026 12:44:09.233" level="FAIL">No keyword with name 'modbus.connection' found.</msg>
<status status="FAIL" starttime="20221026 12:44:09.233" endtime="20221026 12:44:09.253"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>${connection}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" starttime="20221026 12:44:09.302" endtime="20221026 12:44:09.302"/>
</kw>
<kw name="Should Be Equal" library="BuiltIn">
<arg>${connection}</arg>
<arg>${1}</arg>
<doc>Fails if the given objects are unequal.</doc>
<status status="NOT RUN" starttime="20221026 12:44:09.302" endtime="20221026 12:44:09.303"/>
</kw>
<status status="FAIL" starttime="20221026 12:44:09.223" endtime="20221026 12:44:09.304">No keyword with name 'modbus.connection' found.</status>
</test>
<test id="s1-t2" name="Test Cases for POUT" line="20">
<kw name="Create List" library="BuiltIn">
<var>@{pout}</var>
<arg>${17142}</arg>
<arg>${58982}</arg>
<doc>Returns a list containing given items.</doc>
<msg timestamp="20221026 12:44:09.307" level="INFO">@{pout} = [ 17142 | 58982 ]</msg>
<status status="PASS" starttime="20221026 12:44:09.306" endtime="20221026 12:44:09.307"/>
</kw>
<kw name="Log List" library="Collections">
<arg>${pout}</arg>
<doc>Logs the length and contents of the ``list`` using given ``level``.</doc>
<msg timestamp="20221026 12:44:09.314" level="INFO">List length is 2 and it contains following items:
0: 17142
1: 58982</msg>
<status status="PASS" starttime="20221026 12:44:09.313" endtime="20221026 12:44:09.314"/>
</kw>
<kw name="modbus.func_04">
<var>@{fun}</var>
<arg>${30000}</arg>
<arg>${2}</arg>
<msg timestamp="20221026 12:44:09.330" level="FAIL">No keyword with name 'modbus.func_04' found.</msg>
<status status="FAIL" starttime="20221026 12:44:09.329" endtime="20221026 12:44:09.330"/>
</kw>
<kw name="Log List" library="Collections">
<arg>${fun}</arg>
<doc>Logs the length and contents of the ``list`` using given ``level``.</doc>
<status status="NOT RUN" starttime="20221026 12:44:09.332" endtime="20221026 12:44:09.333"/>
</kw>
<kw name="Lists Should Be Equal" library="Collections">
<arg>${fun}</arg>
<arg>${pout}</arg>
<doc>Fails if given lists are unequal.</doc>
<status status="NOT RUN" starttime="20221026 12:44:09.334" endtime="20221026 12:44:09.334"/>
</kw>
<status status="FAIL" starttime="20221026 12:44:09.305" endtime="20221026 12:44:09.334">No keyword with name 'modbus.func_04' found.</status>
</test>
<status status="FAIL" starttime="20221026 12:44:05.911" endtime="20221026 12:44:09.336"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="Serialtest">Serialtest</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221026 12:44:09.163" level="ERROR">Error in file 'c:\project1\First_Repo\serialtest.robot' on line 2: Importing library 'c:\project1\First_Repo\modbus.py' failed: AttributeError: 'ModbusIOException' object has no attribute 'registers'
Traceback (most recent call last):
  File "c:\project1\First_Repo\modbus.py", line 40, in &lt;module&gt;
    func_04(30000,2)
  File "c:\project1\First_Repo\modbus.py", line 36, in func_04
    return ((res.registers))
PYTHONPATH:
  c:\project1\First_Repo
  c:\Users\Shailaja.P\.vscode\extensions\robocorp.robotframework-lsp-1.3.5\src\robotframework_debug_adapter
  C:\project1\First_Repo
  c:\Users\Shailaja.P\.vscode\extensions\robocorp.robotframework-lsp-1.3.5\src
  c:\Users\Shailaja.P\.vscode\extensions\robocorp.robotframework-lsp-1.3.5\src\robotframework_ls\vendored
  C:\Users\Shailaja.P\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\Shailaja.P\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\Shailaja.P\AppData\Local\Programs\Python\Python310\lib
  C:\Users\Shailaja.P\AppData\Local\Programs\Python\Python310
  C:\Users\Shailaja.P\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\Shailaja.P\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\Shailaja.P\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\Shailaja.P\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
</errors>
</robot>
